import cx_Oracle
import pyodbc
import pandas as pd
from config import oracleName, oraclePass, oracleDsn, turboCnxnStr

### ORACLE CONNECTION ###
try:
    iComp = cx_Oracle.connect(
        user=oracleName,
        password=oraclePass,
        dsn=oracleDsn)

    print('Oracle connection successful...')

except cx_Oracle.IntegrityError as e:
    print(e)

### SQL SERVER CONNECTION ###
try:
    cnxnStr = turboCnxnStr
    turbo = pyodbc.connect(cnxnStr)

    print('Turbo connection successful...')

except pyodbc.OperationalError as e:
    print(e)

try:
    oracleQuery = '''
        SELECT 
            CAST(TO_CHAR(SALE_DATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS SALE_DATE
            ,CAST(TO_CHAR(CONNECT_DATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS CONNECT_DATE
            ,CAST(TO_CHAR(CANCEL_DATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS CANCEL_DATE
            ,CAST(TO_CHAR(EVENT_DATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS EVENT_DATE
            ,CAST(TO_CHAR(LEAD_ASSIGN_DATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS LEAD_ASSIGN_DATE
            ,CAST(TO_CHAR(STARTDATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS STARTDATE
            ,CAST(TO_CHAR(ENDDATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS ENDDATE
            ,CAST(TO_CHAR(SUBMIT_ORDER_DATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS SUBMIT_ORDER_DATE
            ,CAST(TO_CHAR(LOADDATETIME, 'YYYY-MM-DD') AS VARCHAR(19)) AS LOADDATETIME
            ,CAST(TO_CHAR(PIPELINESTOPTIME, 'YYYY-MM-DD') AS VARCHAR(19)) AS PIPELINESTOPTIME
            ,CAST(TO_CHAR(MODIFICATIONDATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS MODIFICATIONDATE 
            ,POSITIONSEQ
            ,PIPELINERUNSEQ_CREDIT
            ,PIPELINERUNSEQ_SALETRAN
            ,TRUNC(INSTALL_FEES,2) AS INSTALL_FEES
            ,TRUNC(NRC,2) AS NRC
            ,TRUNC(PRI_DISCOUNT,2) AS PRI_DISCOUNT
            ,TRUNC(HOSPITALITY_DISCOUNT,2) AS HOSPITALITY_DISCOUNT
            ,TRUNC(PRIMARY_SIP_REVENUE,2) AS PRIMARY_SIP_REVENUE
            ,SECONDARY_SIP_REVENUE
            ,TRUNC(SIP_REVENUE,2) AS SIP_REVENUE
            ,TRUNC(PRIMARY_EOHFC_REVENUE,2) AS PRIMARY_EOHFC_REVENUE
            ,SECONDARY_EOHFC_REVENUE
            ,TRUNC(EOHFC_REVENUE,2) AS EOHFC_REVENUE
            ,TRUNC(PRIMARY_BVE_REVENUE,2) AS PRIMARY_BVE_REVENUE
            ,TRUNC(SECONDARY_BVE_REVENUE,2) AS SECONDARY_BVE_REVENUE
            ,TRUNC(BVE_REVENUE,2) AS BVE_REVENUE
            ,BVE_DISCOUNT
            ,TRUNC(PERF_MONTH,2) AS PERF_MONTH
            ,TRUNC(SO_DISCOUNT,2) AS SO_DISCOUNT
            ,TRUNC(NO_OF_TOLL_FREE,2) AS NO_OF_TOLL_FREE
            ,TRUNC(PROMO_$,2) AS PROMO_$
            ,TRUNC(PRIMARY_SO_REVENUE,2) AS PRIMARY_SO_REVENUE
            ,TRUNC(DATA_DISCOUNT,2) AS DATA_DISCOUNT
            ,TRUNC(SECONDARY_DATA_REVENUE,2) AS SECONDARY_DATA_REVENUE
            ,TRUNC(SECONDARY_VOICE_REVENUE,2) AS SECONDARY_VOICE_REVENUE
            ,TRUNC(SO_REVENUE,2) AS SO_REVENUE
            ,TRUNC(SECONDARY_SO_REVENUE,2) AS SECONDARY_SO_REVENUE
            ,TRUNC(VIDEO_DISCOUNT,2) AS VIDEO_DISCOUNT
            ,TRUNC(VOICE_DISCOUNT,2) AS VOICE_DISCOUNT
            ,TRUNC(PRIMARY_DATA_REVENUE,2) AS PRIMARY_DATA_REVENUE
            ,TRUNC(SECONDARY_VIDEO_REVENUE,2) AS SECONDARY_VIDEO_REVENUE
            ,TRUNC(SECONDARY_PRI_REVENUE,2) AS SECONDARY_PRI_REVENUE
            ,TRUNC(DATA_REVENUE,2) AS DATA_REVENUE
            ,TRUNC(VIDEO_REVENUE,2) AS VIDEO_REVENUE
            ,TRUNC(PRI_REVENUE,2) AS PRI_REVENUE
            ,TRUNC(PRIMARY_VIDEO_REVENUE,2) AS PRIMARY_VIDEO_REVENUE
            ,TRUNC(PRIMARY_PRI_REVENUE,2) AS PRIMARY_PRI_REVENUE
            ,TRUNC(CONSTRUCTION_$,2) AS CONSTRUCTION_$
            ,TRUNC(DISCOUNT,2) AS DISCOUNT
            ,TRUNC(VOICE_REVENUE,2) AS VOICE_REVENUE
            ,TRUNC(PRIMARY_VOICE_REVENUE,2) AS PRIMARY_VOICE_REVENUE
            ,PERIODSEQ,PIPELINEPERIODSEQ
            ,SUBSTR(TRIM(NUMBER_VOICE_LINES),1,4 ) AS NUMBER_VOICE_LINES 
            ,SUBSTR(TRIM(NUMBER_CBM_LINES),1,4 ) AS NUMBER_CBM_LINES
            ,SUBSTR(TRIM(SIP_EXISTING),1,4 ) AS SIP_EXISTING
            ,SUBSTR(TRIM(ADDL_SIP),1,4 ) AS ADDL_SIP
            ,SUBSTR(TRIM(EOHFC_EXISTING),1,4 ) AS EOHFC_EXISTING
            ,SUBSTR(TRIM(ADDL_EOHFC),1,4 ) AS ADDL_EOHFC
            ,SUBSTR(TRIM(BVE_EXISTING),1,4 ) AS BVE_EXISTING
            ,SUBSTR(TRIM(ADDL_BVE),1,4 ) AS ADDL_BVE
            ,SUBSTR(TRIM(DATA_EXISTING),1,5 ) AS DATA_EXISTING
            ,SUBSTR(TRIM(ADDL_MODEM),1,5 ) AS ADDL_MODEM
            ,SUBSTR(TRIM(DATA_SOLD),1,5 ) AS DATA_SOLD
            ,SUBSTR(TRIM(VIDEO_EXISTING),1,5 ) AS VIDEO_EXISTING
            ,SUBSTR(TRIM(VOICE_EXISTING),1,5 ) AS VOICE_EXISTING
            ,SUBSTR(TRIM(ADDL_LINES),1,5 ) AS ADDL_LINES
            ,SUBSTR(TRIM(PRI_EXISTING),1,5 ) AS PRI_EXISTING
            ,SUBSTR(TRIM(ADDL_PRI),1,5 ) AS ADDL_PRI
            ,SUBSTR(TRIM(CHANNELS),1,5 ) AS CHANNELS
            ,SUBSTR(TRIM(VIDEO_SOLD),1,5 ) AS VIDEO_SOLD
            ,SUBSTR(TRIM(VOICE_SOLD),1,5 ) AS VOICE_SOLD
            ,SUBSTR(TRIM(PRI_SOLD),1,5 ) AS PRI_SOLD
            ,SUBSTR(TRIM(SO_EXISTING),1,5 ) AS SO_EXISTING
            ,SUBSTR(TRIM(PRIMARY_PRI_PRODUCT),1,10 ) AS PRIMARY_PRI_PRODUCT
            ,SUBSTR(TRIM(PRIMARY_VOICE_PRODUCT),1,18 ) AS PRIMARY_VOICE_PRODUCT
            ,SUBSTR(TRIM(VIDEO_PRIMARY_PRODUCT),1,21 ) AS VIDEO_PRIMARY_PRODUCT
            ,SUBSTR(TRIM(DATA_PRIMARY_PRODUCT_NAME),1,43 ) AS DATA_PRIMARY_PRODUCT_NAME
            ,SUBSTR(TRIM(DELEGATE_FIRST_NAME),1,2 ) AS DELEGATE_FIRST_NAME
            ,SUBSTR(TRIM(DELEGATE_LAST_NAME),1,2 ) AS DELEGATE_LAST_NAME
            ,SUBSTR(TRIM(TERM),1,4 ) AS TERM
            ,SUBSTR(TRIM(PRI_TRANSFER_IND),1,4 ) AS PRI_TRANSFER_IND
            ,SUBSTR(TRIM(BILLING_SYSTEM),1,5 ) AS BILLING_SYSTEM
            ,SUBSTR(TRIM(EXISTING_CUSTOMER),1,5 ) AS EXISTING_CUSTOMER
            ,SUBSTR(TRIM(SERVICEABILITY),1,5 ) AS SERVICEABILITY
            ,SUBSTR(TRIM(REGION_CODE),1,5 ) AS REGION_CODE
            ,SUBSTR(TRIM(DIVISION_CODE),1,5 ) AS DIVISION_CODE
            ,SUBSTR(TRIM(RENEWAL_FLAG),1,5 ) AS RENEWAL_FLAG
            ,SUBSTR(TRIM(SO_SOLD),1,5 ) AS SO_SOLD
            ,SUBSTR(TRIM(SIP_SOLD),1,5 ) AS SIP_SOLD
            ,SUBSTR(TRIM(SIP_PRIMARY_PRODUCT_NAME),1,5 ) AS SIP_PRIMARY_PRODUCT_NAME
            ,SUBSTR(TRIM(EOHFC_SOLD),1,5 ) AS EOHFC_SOLD
            ,SUBSTR(TRIM(BVE_SOLD),1,5 ) AS BVE_SOLD
            ,SUBSTR(TRIM(BVE_PRIMARY_PRODUCT_NAME),1,5 ) AS BVE_PRIMARY_PRODUCT_NAME
            ,SUBSTR(TRIM(ATTACHMENT_TYPE),1,9 ) AS ATTACHMENT_TYPE
            ,SUBSTR(TRIM(REP_SCOPE),1,10 ) AS REP_SCOPE
            ,SUBSTR(TRIM(PERNR),1,11 ) AS PERNR
            ,SUBSTR(TRIM(NETWORK_TYPE),1,11 ) AS NETWORK_TYPE
            ,SUBSTR(TRIM(SURVEY_TYPE),1,12 ) AS SURVEY_TYPE
            ,SUBSTR(TRIM(STATE),1,14 ) AS STATE
            ,SUBSTR(TRIM(SO_PRIMARY_PRODUCT_NAME),1,14 ) AS SO_PRIMARY_PRODUCT_NAME
            ,SUBSTR(TRIM(PARENT_ACCOUNT_ID),1,15 ) AS PARENT_ACCOUNT_ID
            ,SUBSTR(TRIM(ROOT_ACCOUNT_ID),1,15 ) AS ROOT_ACCOUNT_ID
            ,SUBSTR(TRIM(DELEGATE_PERNR),1,16 ) AS DELEGATE_PERNR
            ,SUBSTR(TRIM(SITE_ID),1,16 ) AS SITE_ID
            ,SUBSTR(TRIM(NTLOGIN),1,19 ) AS NTLOGIN
            ,SUBSTR(TRIM(REP_TYPE),1,19 ) AS REP_TYPE
            ,SUBSTR(TRIM(CONTRACT_ATTACHMENT),1,19 ) AS CONTRACT_ATTACHMENT
            ,SUBSTR(TRIM(EOHFC_PRIMARY_PRODUCT_NAME),1,19 ) AS EOHFC_PRIMARY_PRODUCT_NAME
            ,SUBSTR(TRIM(DIVISION),1,20 ) AS DIVISION
            ,SUBSTR(TRIM(SAVILLE_ACCOUNT_NUMBER),1,21 ) AS SAVILLE_ACCOUNT_NUMBER
            ,SUBSTR(TRIM(TRAN_DIVISION),1,21 ) AS TRAN_DIVISION
            ,SUBSTR(TRIM(ZIP),1,22 ) AS ZIP
            ,SUBSTR(TRIM(ACCOUNT_NUMBER),1,22 ) AS ACCOUNT_NUMBER
            ,SUBSTR(TRIM(WB_REP_LOGIN_ID),1,22 ) AS WB_REP_LOGIN_ID
            ,SUBSTR(TRIM(CANCEL_OWNER_FIRST_NAME),1,24 ) AS CANCEL_OWNER_FIRST_NAME
            ,SUBSTR(TRIM(ACCOUNT_SCOPE),1,24 ) AS ACCOUNT_SCOPE
            ,SUBSTR(TRIM(TRAN_REGION),1,25 ) AS TRAN_REGION
            ,SUBSTR(TRIM(SF_ACCOUNT_ID),1,25 ) AS SF_ACCOUNT_ID
            ,SUBSTR(TRIM(MULTI_SITE_INDICATOR),1,26 ) AS MULTI_SITE_INDICATOR
            ,SUBSTR(TRIM(CANCEL_OWNER_LAST_NAME),1,26 ) AS CANCEL_OWNER_LAST_NAME
            ,SUBSTR(TRIM(CANCEL_OWNER_PERNR),1,26 ) AS CANCEL_OWNER_PERNR
            ,SUBSTR(TRIM(REGION),1,32 ) AS REGION
            ,SUBSTR(TRIM(CITY),1,32 ) AS CITY
            ,SUBSTR(TRIM(LEAD_SCOURCE),1,36 ) AS LEAD_SCOURCE
            ,SUBSTR(TRIM(VERTICAL),1,37 ) AS VERTICAL
            ,SUBSTR(TRIM(CAMPAIGN_CODE),1,37 ) AS CAMPAIGN_CODE
            ,SUBSTR(TRIM(PACKAGE_CODE),1,37 ) AS PACKAGE_CODE
            ,SUBSTR(TRIM(OA_OWNER_PERNR),1,38 ) AS OA_OWNER_PERNR
            ,SUBSTR(TRIM(PROMO),1,40 ) AS PROMO
            ,SUBSTR(TRIM(CORP_SYSPRIN),1,49 ) AS CORP_SYSPRIN
            ,SUBSTR(TRIM(CORP_SYSPRIN_CODE),1,49 ) AS CORP_SYSPRIN_CODE
            ,SUBSTR(TRIM(ROLE),1,50 ) AS ROLE
            ,SUBSTR(TRIM(ADDRESS_1),1,52 ) AS ADDRESS_1
            ,SUBSTR(TRIM(CANCEL_REASON),1,52 ) AS CANCEL_REASON
            ,SUBSTR(TRIM(BUNDLE),1,59 ) AS BUNDLE
            ,SUBSTR(TRIM(OA_TASK_OWNER),1,72 ) AS OA_TASK_OWNER
            ,SUBSTR(TRIM(ACCOUNT_NAME),1,95 ) AS ACCOUNT_NAME
            ,SUBSTR(TRIM(ADDRESS_2),1,240 ) AS ADDRESS_2
            ,SUBSTR(TRIM(PROMO_DESCRIPTION),1,257 ) AS PROMO_DESCRIPTION
            ,SUBSTR(TRIM(PACKAGE_DESC),1,257 ) AS PACKAGE_DESC
            ,SUBSTR(TRIM(SUBID),1,4 ) AS SUBID
            ,SUBSTR(TRIM(SALE),1,6 ) AS SALE
            ,SUBSTR(TRIM(CANCEL1),1,8 ) AS CANCEL1
            ,SUBSTR(TRIM(CONNECT1),1,9 ) AS CONNECT1
            ,SUBSTR(TRIM(EVENT_TYPE),1,13 ) AS EVENT_TYPE
            ,SUBSTR(TRIM(ORDERID),1,26 ) AS ORDERID
            ,SUBSTR(TRIM(PERIODNAME),1,2 ) AS PERIODNAME
            ,CAST(TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS VARCHAR(19)) AS RECORD_CREATE_DATE
            ,SUBSTR(TRIM(DATA_PRODUCT_BEFORE),1,43 ) as DATA_PRODUCT_BEFORE
            ,SUBSTR(TRIM(DATA_PRODUCT_AFTER),1,43 ) as DATA_PRODUCT_AFTER
            ,TRUNC(DATA_STARTING,2) AS DATA_STARTING
            ,TRUNC(DATA_ENDING,2) AS DATA_ENDING
            ,SUBSTR(TRIM(VIDEO_PRODUCT_BEFORE),1,21 ) as VIDEO_PRODUCT_BEFORE
            ,SUBSTR(TRIM(VIDEO_PRODUCT_AFTER),1,21 ) as VIDEO_PRODUCT_AFTER
            ,TRUNC(VIDEO_STARTING,2) AS VIDEO_STARTING
            ,TRUNC(VIDEO_ENDING,2) AS VIDEO_ENDING
            ,SUBSTR(TRIM(VOICE_PRODUCT_BEFORE),1,18 ) as VOICE_PRODUCT_BEFORE
            ,SUBSTR(TRIM(VOICE_PRODUCT_AFTER),1,18 ) as VOICE_PRODUCT_AFTER
            ,TRUNC(VOICE_STARTING,2) AS VOICE_STARTING
            ,TRUNC(VOICE_ENDING,2) AS VOICE_ENDING
            ,SUBSTR(TRIM(PRI_PRODUCT_BEFORE),1,10 ) as PRI_PRODUCT_BEFORE
            ,SUBSTR(TRIM(PRI_PRODUCT_AFTER),1,10 ) as PRI_PRODUCT_AFTER
            ,TRUNC(PRI_STARTING,2) AS PRI_STARTING
            ,TRUNC(PRI_ENDING,2) AS PRI_ENDING
            ,SUBSTR(TRIM(BVE_PRODUCT_BEFORE),1,5 ) as BVE_PRODUCT_BEFORE
            ,SUBSTR(TRIM(BVE_PRODUCT_AFTER),1,5 ) as BVE_PRODUCT_AFTER
            ,TRUNC(BVE_STARTING,2) AS BVE_STARTING
            ,TRUNC(BVE_ENDING,2) AS BVE_ENDING
            ,SUBSTR(TRIM(SO_PRODUCT_BEFORE),1,14 ) as SO_PRODUCT_BEFORE
            ,SUBSTR(TRIM(SO_PRODUCT_AFTER),1,14 ) as SO_PRODUCT_AFTER
            ,TRUNC(SO_STARTING,2) AS SO_STARTING
            ,TRUNC(SO_ENDING,2) AS SO_ENDING
            ,SUBSTR(TRIM(EOHFC_PRODUCT_BEFORE),1,19 ) as EOHFC_PRODUCT_BEFORE
            ,SUBSTR(TRIM(EOHFC_PRODUCT_AFTER),1,19 ) as EOHFC_PRODUCT_AFTER
            ,TRUNC(EOHFC_STARTING,2) AS EOHFC_STARTING
            ,TRUNC(EOHFC_ENDING,2) AS EOHFC_ENDING
            ,SUBSTR(TRIM(SIP_PRODUCT_BEFORE),1,5 ) as SIP_PRODUCT_BEFORE
            ,SUBSTR(TRIM(SIP_PRODUCT_AFTER),1,5 ) as SIP_PRODUCT_AFTER
            ,TRUNC(SIP_STARTING,2) AS SIP_STARTING
            ,TRUNC(SIP_ENDING,2) AS SIP_ENDING
        FROM 
            TCPRB01RPT.Z_CMART_TRANSACTIONDATA
        WHERE
            LOADDATETIME >= DATE '2020-12-22'
        '''

    oracleDf = pd.read_sql(oracleQuery, con=iComp)

    print('Pulled historical successfully...')

except cx_Oracle.IntegrityError as e:
    print(e)

print(oracleDf.head())